package com.aliyun.odps.datacarrier.taskscheduler;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class TestMmaConfig {
  private static final Logger LOG = LogManager.getLogger(TestMmaConfig.class);

  // Existing test resources
  private static final Path resourcesDir =  Paths.get("src",
                                                      "test",
                                                      "resources");
  private static final Path odpsConfigPath = Paths.get(resourcesDir.toString(),
                                                       "odps_config.ini");
  private static final Path hiveConfigPath = Paths.get(resourcesDir.toString(),
                                                       "hive_config.ini");
  private static final Path tableMappingPath = Paths.get(resourcesDir.toString(),
                                                         "table_mapping.txt");

  // Files generated by this test
  private static final Path mmaClientConfigPath = Paths.get("mma_client_config.json");
  private static final Path mmaServerConfigPath = Paths.get("mma_server_config.json");
  private static final Path mmaMigrationConfigPath = Paths.get("mma_migration_config.json");

  @BeforeClass
  public static void beforeClass() {
    // Remove previous generated config files
    assert !mmaClientConfigPath.toFile().exists() || mmaClientConfigPath.toFile().delete();
    assert !mmaServerConfigPath.toFile().exists() || mmaServerConfigPath.toFile().delete();
    assert !mmaMigrationConfigPath.toFile().exists() || mmaMigrationConfigPath.toFile().delete();

    // Ensure required test resources exist
    if (!odpsConfigPath.toFile().exists()
        || !hiveConfigPath.toFile().exists()
        || !tableMappingPath.toFile().exists()) {
      throw new IllegalStateException("Test resources for TestMmaConfig not found");
    }
  }

  @AfterClass
  public static void afterClass() {
    // Remove generated config files
    assert !mmaClientConfigPath.toFile().exists() || mmaClientConfigPath.toFile().delete();
    assert !mmaServerConfigPath.toFile().exists() || mmaServerConfigPath.toFile().delete();
    assert !mmaMigrationConfigPath.toFile().exists() || mmaMigrationConfigPath.toFile().delete();
  }

  @Test (timeout = 5000)
  public void testGenerateMmaClientConfig() throws IOException {
    MmaConfigUtils.generateMmaClientConfig(hiveConfigPath, "");
    MmaClientConfig mmaClientConfig = MmaClientConfig.fromFile(mmaClientConfigPath);

    // Datasource
    assertEquals(DataSource.Hive, mmaClientConfig.getDataSource());

    // Hive config
    checkHiveConfig(mmaClientConfig.getHiveConfig());

    // ODPS config and OSS config should be null
    assertNull(mmaClientConfig.getOdpsConfig());
    assertNull(mmaClientConfig.getOssConfig());
  }

  @Test (timeout = 5000)
  public void testGenerateMmaServerConfig() throws IOException {
    MmaConfigUtils.generateMmaServerConfig(hiveConfigPath, odpsConfigPath, "");
    MmaServerConfig mmaServerConfig = MmaServerConfig.fromFile(mmaServerConfigPath);

    // Datasource
    assertEquals(DataSource.Hive, mmaServerConfig.getDataSource());

    // Hive config
    checkHiveConfig(mmaServerConfig.getHiveConfig());

    // ODPS config
    checkOdpsConfig(mmaServerConfig.getOdpsConfig());

    // OSS config should be null
    assertNull(mmaServerConfig.getOssConfig());
  }

  @Test (timeout = 5000)
  public void testGenerateMmaMigrationConfig() throws IOException {
    MmaConfigUtils.generateMmaMigrationConfig(tableMappingPath, "");
    MmaMigrationConfig mmaMigrationConfig = MmaMigrationConfig.fromFile(mmaMigrationConfigPath);

    assertNotNull(mmaMigrationConfig.getTableMigrationConfigs());
    assertEquals(2, mmaMigrationConfig.getTableMigrationConfigs().size());

    MmaConfig.TableMigrationConfig tableMigrationConfig1 =
        mmaMigrationConfig.getTableMigrationConfigs().get(0);
    assertEquals("hive_test_db", tableMigrationConfig1.getSourceDataBaseName());
    assertEquals("hive_test_tbl1" ,tableMigrationConfig1.getSourceTableName());
    assertEquals("mc_test_project", tableMigrationConfig1.getDestProjectName());
    assertEquals("mc_test_table1", tableMigrationConfig1.getDestTableName());
    checkAdditionalTableConfig(tableMigrationConfig1.getAdditionalTableConfig());

    MmaConfig.TableMigrationConfig tableMigrationConfig2 =
        mmaMigrationConfig.getTableMigrationConfigs().get(1);
    assertEquals("hive_test_db", tableMigrationConfig2.getSourceDataBaseName());
    assertEquals("hive_test_tbl2" ,tableMigrationConfig2.getSourceTableName());
    assertEquals("mc_test_project", tableMigrationConfig2.getDestProjectName());
    assertEquals("mc_test_table2", tableMigrationConfig2.getDestTableName());
    checkAdditionalTableConfig(tableMigrationConfig2.getAdditionalTableConfig());
  }

  private void checkHiveConfig(MmaConfig.HiveConfig hiveConfig) {
    assertEquals("test_connection_url", hiveConfig.getJdbcConnectionUrl());
    assertEquals("test_user", hiveConfig.getUser());
    assertEquals("test_password", hiveConfig.getPassword());
    assertEquals("test_hms_thrift_addr", hiveConfig.getHmsThriftAddr());
    assertNull(hiveConfig.getKeyTab());
    assertNull(hiveConfig.getKrbPrincipal());
    assertNull(hiveConfig.getKrbSystemProperties());
    assertEquals(7, hiveConfig.getHiveJdbcExtraSettings().size());
  }

  private void checkOdpsConfig(MmaConfig.OdpsConfig odpsConfig) {
    assertEquals("test_project_name", odpsConfig.getProjectName());
    assertEquals("test_access_id", odpsConfig.getAccessId());
    assertEquals("test_access_key", odpsConfig.getAccessKey());
    assertEquals("test_end_point", odpsConfig.getEndpoint());
    assertNull(odpsConfig.getTunnelEndpoint());
  }

  private void checkAdditionalTableConfig(MmaConfig.AdditionalTableConfig additionalTableConfig) {
    assertEquals(3, additionalTableConfig.getRetryTimesLimit());
    assertEquals(100, additionalTableConfig.getPartitionGroupSize());
    assertNull(additionalTableConfig.getColumnNameCustomizedConversion());
    assertNull(additionalTableConfig.getTypeCustomizedConversion());
  }

  // TODO: add test for MmaMigrationConfig, MmaClientConfig and MmaServerConfig
}
